"""Initial schema - fixed UUID types

Revision ID: 95ec8fddf9ad
Revises: 
Create Date: 2026-06-17 20:28:46.567228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ec8fddf9ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=150), nullable=True),
    sa.Column('rfc', sa.String(length=20), nullable=False),
    sa.Column('regimen_fiscal', sa.String(length=50), nullable=False),
    sa.Column('codigo_postal', sa.String(length=10), nullable=False),
    sa.Column('representante_legal', sa.String(length=150), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('configuracion_contable', sa.JSON(), nullable=True),
    sa.Column('serie_factura', sa.String(length=10), nullable=True),
    sa.Column('folio_actual', sa.Integer(), nullable=True),
    sa.Column('moneda_base', sa.String(length=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfc')
    )
    op.create_table('categorias',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('esta_activa', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marcas',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('esta_activa', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('roles',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('es_sistema', sa.Boolean(), nullable=True),
    sa.Column('permisos', sa.JSON(), nullable=True),
    sa.Column('nivel_acceso', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('sucursales',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('rfc', sa.String(length=20), nullable=True),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('marca_id', sa.UUID(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('tipo_producto', sa.String(length=50), nullable=False),
    sa.Column('unidad_medida', sa.String(length=20), nullable=True),
    sa.Column('costo_estandar', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('precio_mayoreo', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('metodo_costeo', sa.String(length=20), nullable=True),
    sa.Column('stock_minimo', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('stock_maximo', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('punto_reorden', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('requiere_receta', sa.Boolean(), nullable=True),
    sa.Column('es_servicio', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('usuarios',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('sucursal_id', sa.UUID(), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=True),
    sa.Column('email_verificado', sa.Boolean(), nullable=True),
    sa.Column('mfa_habilitado', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=32), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=True),
    sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferencias', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('sesiones',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('dispositivo', sa.String(length=100), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('es_activa', sa.Boolean(), nullable=True),
    sa.Column('ultima_actividad', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_token_hash'), 'sesiones', ['token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sesiones_token_hash'), table_name='sesiones')
    op.drop_table('sesiones')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('sucursales')
    op.drop_table('roles')
    op.drop_table('marcas')
    op.drop_table('categorias')
    op.drop_table('empresas')
    # ### end Alembic commands ###