#!/usr/bin/env python3
"""Create a coherent, production-oriented root .env without committing secrets."""

from __future__ import annotations

import argparse
import secrets
from pathlib import Path
from urllib.parse import quote


ROOT = Path(__file__).resolve().parents[1]


def token(length: int = 32) -> str:
    return secrets.token_urlsafe(length)


def render(*, domain: str, postgres_host: str, mongo_host: str, redis_host: str) -> str:
    postgres_password = token()
    mongo_password = token()
    redis_password = token()
    secret_key = token(48)
    pg_encoded = quote(postgres_password, safe="")
    mongo_encoded = quote(mongo_password, safe="")
    return f"""# Generated by scripts/init_production_environment.py.
# Store this file securely; never commit it.
OPTICA_POSTGRES_USER=optica_user
OPTICA_POSTGRES_PASSWORD={postgres_password}
OPTICA_POSTGRES_DB=optica_system

OPTICA_MONGO_USER=optica_admin
OPTICA_MONGO_PASSWORD={mongo_password}
OPTICA_MONGO_DB=optica_clinico

DATABASE_URL=postgresql+asyncpg://optica_user:{pg_encoded}@{postgres_host}:5432/optica_system
REDIS_PASSWORD={redis_password}
REDIS_URL=redis://:{quote(redis_password, safe="")}@{redis_host}:6379/0
MONGODB_URL=mongodb://optica_admin:{mongo_encoded}@{mongo_host}:27017/optica_clinico?authSource=admin

ENVIRONMENT=production
DEBUG=false
SECRET_KEY={secret_key}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=7
CORS_ORIGINS=[\"https://{domain}\"]

CFDI_PROVIDER=HTTP
CFDI_API_URL=https://cfdi-provider.invalid
CFDI_API_KEY=replace-with-secret-manager-reference
CFDI_TIMEOUT_SECONDS=10
CFDI_RETRY_ATTEMPTS=3

BANKING_PROVIDER=HTTP
BANKING_API_URL=https://banking-provider.invalid
BANKING_API_KEY=replace-with-secret-manager-reference
BANKING_TIMEOUT_SECONDS=10
BANKING_RETRY_ATTEMPTS=3

VITE_API_BASE_URL=
APP_BIND_ADDRESS=127.0.0.1
APP_PORT=8080
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / ".env")
    parser.add_argument("--domain", required=True, help="Dominio público del frontend")
    parser.add_argument("--postgres-host", default="postgres")
    parser.add_argument("--mongo-host", default="mongodb")
    parser.add_argument("--redis-host", default="redis")
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output.resolve()
    if output.exists() and not args.force:
        print(f"ERROR: {output} ya existe; use --force para reemplazarlo")
        return 1
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        render(
            domain=args.domain,
            postgres_host=args.postgres_host,
            mongo_host=args.mongo_host,
            redis_host=args.redis_host,
        ),
        encoding="utf-8",
    )
    output.chmod(0o600)
    print(f"✅ entorno generado en {output} con permisos 0600")
    print("Reemplace las credenciales de proveedores por referencias del gestor de secretos.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
